GET http://localhost:3003/api/users/
Content-Type: application/json

# {
#     "blogs": [],
#     "name": "Alisa Liubarskaia",
#     "username": "aliubarskaia",
#     "password": "12345"
# }

# {
#     "title": "Miracle happend yesterday",
#     "author": "Leevi",
#     "url": "idk",
#     "likes": 20,
#     "userId" : "658ec53f9c99365165568188"
# }




