POST http://localhost:3003/api/testing/reset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaXViYXJza2FpYSIsImlkIjoiNjU4ZWRjNDc2ZWNlZjg4MDNhNWQyZDk0IiwiaWF0IjoxNzA1OTMyMDg4fQ.kBqnll-fw_oxfNpE70duyBozTebAn2wR70hJLuxj5FE

{
    "title": "TEST WITH URL",
    "author": "Tuomas Kyrö",
    "url": "http:/something",
    "likes": 12
}

# {
#     "username": "aliubarskaia",
#     "password": "12345"
# }




# {
#     "username": "aliubarskaia",
#     "password": "12345"
# }

# {
#     "blogs": [],
#     "name": "Alisa Liubarskaia",
#     "username": "aliubarskaia",
#     "password": "12345"
# }






